version: 2
updates:
  # Enable version updates for bun
  - package-ecosystem: "bun"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # # Enable version updates for mix (erlang, elixir, gleam, etc.)
  # - package-ecosystem: "mix"
  #   directory: "/"
  #   # Check for updates once a week
  #   schedule:
  #     interval: "weekly"
