name = "chore_tracker"
version = "1.0.0"
target = "javascript"

description = "Prototype chore tracker implementation using Gleam/Lustre/DaisyUI"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "afarinetti", repo = "https://github.com/afarinetti/chore-tracker-gleam" }

[javascript]
typescript_declarations = true
runtime = "bun"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.1 and < 3.0.0"

[tools.lustre.bin]
bun = "system"
tailwindcss = "./node_modules/.bin/tailwindcss"

[tools.lustre.html]
title = "Chore Tracker"

[tools.lustre.build]
minify = true
